config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process

  mount ActionCable.server => '/cable'

  root to: 'static#home'
  get '/coming_soon', to: 'static#coming_soon'
  get '/que_es', to: 'static#que_es'
  get '/como_funciona', to: 'static#como_funciona'
  get '/testimonios', to: 'static#testimonios'
  get '/contacto', to: 'static#contacto'

  get '/my_dashboard',  to: 'users#dashboard', as: 'user_dashboard'

  get '/my_referrals',  to: 'users#my_referrals'

  post '/send_donation',  to: 'users#donation_send'

  post '/request_donation', to: 'users#donation_request'

  post '/add_invoice', to: 'transactions#add_invoice'

  get '/confirm_transaction', to: 'transactions#confirm_transaction', as: 'transaction_confirm'

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :donations

  resources :chats do
    resources :messages
  end

  get '/coming_soon',  to: 'static#coming_soon', as: 'coming'

  get '/account_balance',  to: 'users#account_balance'

  get '/news',  to: 'users#news'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  has_many :chats, :foreign_key => :sender_id
  has_many :donations
  has_many :requests
  before_save :set_saldo_zero
  acts_as_tree order: "email"
  extend ActsAsTree::TreeView
  attr_accessor :refferal



  def set_saldo_zero
    self.saldo ||= 0
  end
  
  
  def send_donation (value)

    #Configuración de variables para inicializar la donación
  
    request = get_oldest_request() #Tomar el request mas antiguo

    donation_value = value.round() #valor de la donacion ingresada  
    
    residuo = donation_value #valor pendiente por entregar de la donación, campo pending de la donación

    donation_state = 0  #estado de la donación, si ya ha sido repartida o aun no. 
    
    donation = self.donations.create(value: donation_value, pending: residuo, status: donation_state)
    
    #revisar resultados del metodo mientras haya residuo y la cola se puede actualziar con transacciones pendientes volver a repartir

    while((donation.pending > 0) && request )

        create_transaction(request, donation, residuo) 
        #Funcion para realizar el envio con las variables configuradas
        request = get_oldest_request() #Tomar el request mas antiguo
  
    end

    donation.id

  end
  
  
  def create_transaction(request, donation, residuo)
    #repartir la donación en el request
    #Inicializar valores para calcular la transacción
    #valor a entregar por transacción 
    transaction_value = 0
    #estado del  request
    request_state = 0
    #estado de la donacion
    donation_state = 0

    if request.pending > donation.pending || request.pending == donation.pending

       transaction_value = donation.pending
       residuo = 0

    elsif request.pending < donation.pending

       transaction_value = request.pending
       residuo = donation.pending - transaction_value
       
    end
    #crear la transacción
    transaction = donation.transactions.create(value: transaction_value, sender_id: donation.user_id, receiver_id: request.user_id, request_id: request.id)
   
    #hacer update de la donación
    #Actualizar estado de la donacion 
    if residuo==0
      donation_state = 1
    end

    donation.update(pending: residuo, status: donation_state)

    #actualizar valores  del request  
    pending = request.pending - transaction_value

    if pending == 0 
      request_state = 1
    end

    request.update(pending: pending, requested: request_state)

    #imprimir valores al final del proceso

    p "El usuario que solicito la transacción  #{request.user_id}"
    p "El usuario que recibirá la transaccon  es  #{transaction.receiver_id}"
    p "El valor solicitado es #{request.value}"
    p "El valor a consignar es #{transaction.value}" 
    p "El valor pendiente del request es #{request.pending}" 
    p "El residuo de la donación es  #{donation.pending}"
    p "El estado del request es #{request.requested}"
    p "El estado de la donación es #{donation.status}"

  end
        
  def get_oldest_request
    
    block = Request.where.not(user_id: self.id)
    block = block.where(requested: "waiting")
    block.order('created_at DESC').last()

  end

  def request_donation(value)

    request_value = value.round()
    residuo = request_value #valor pendiente por ser requerido del request
    request_state = 0  #estado del request si aun no ha sido asignada

    #creo el request con el valor asignado
    request = self.requests.create(value: request_value, pending: residuo)

    #busco si hay donaciones pendientes por repartir
    donation =  get_pending_donation

    self.update(saldo: self.saldo - request_value)
    
    if donation

      while((request.pending > 0) && donation )
          create_transaction(request, donation, residuo) 
          #revisar si aun hay donaciones que puedan repartir
          donation =  get_pending_donation
      end

    end

  end

  def get_pending_donation
  
    block = Donation.where.not(user_id: self.id)
    block = block.where(status: "pending")
    block.order('created_at DESC').last()

  end

end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def dashboard
      @donations = current_user.donations.order('created_at DESC')
      @requests = current_user.requests.order('created_at DESC')
      render layout: "dashboard_layout"
    end

    def donation_send
        if params[:value]
            if   current_user.send_donation(donation_params[:value].to_i)
                redirect_to '/my_dashboard',  :notice => "Donation sucessfully sent" 
            else
                redirect_to '/my_dashboard', :notice => "Invalid donation value" 
            end
        else
            redirect_to '/my_dashboard', :notice => "No donation value specified" 
        end
    end

    def donation_request
      if params[:value]
        current_user.request_donation(donation_params[:value].to_i)
        redirect_to '/my_dashboard', :notice => "Request succesfully sent" 
      else
        redirect_to '/my_dashboard', :notice => "Invalid donation value" 
      end
    end

    def my_referrals
       @current_user_children = current_user.children
       render layout: "dashboard_layout"
    end

    def account_balance
        @donations = current_user.donations
        @requests = current_user.requests
        render layout: "dashboard_layout"
    end

    def news
        render layout: "dashboard_layout"
    end
private
    def donation_params
      params.permit(:value)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_donation_list.html.erb
        
            <div class="well span8 offset2">
                <div class="row-fluid user-row">
                    <div class="span10">
                        <strong>Code: DGDN<%= donation.id %></strong><br>
                         <strong>Value: <%= donation.value %></strong>
                       
                    </div>
                    <div class="span1 dropdown-user" data-for=".<%= donation.id%>">
                        <i class="icon-chevron-down text-muted"></i>
                    </div>
                </div>
                <div class="row-fluid user-infos <%= donation.id%>">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">Donation information</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row-fluid">
                                <div class="span6">
                                    <table class="table table-condensed table-responsive table-user-information">
                                        <tbody>
                                        <tr>
                                            <td>Value:</td>
                                            <td><%= donation.value %></td>
                                        </tr>
                                        <tr>
                                            <td>Date:</td>
                                            <td><%= donation.created_at.to_date %></td>
                                        </tr>
                                        <tr>
                                            <td>Status:</td>
                                            <% if donation.completed %>
                                                <td>Completed</td>
                                            <% elsif donation.status == "pending"  %>
                                                <td>Pending for requests</td>
                                            <% else donation.status == "completed"  %>
                                                <td>Pending for transactions completion</td>
                                            <% end %>
                                        </tr>
                                        <tr>
                                            <td>Value pending to be requested</td>
                                            <td><%= donation.pending %></td>
                                        </tr>
                                        <tr>
                                            <td>Total transactions</td>
                                            <td><%= donation.transactions.count %></td>
                                        </tr>
                                        <tr>
                                            <td>Completed transactions</td>
                                            <td><%= donation.transactions.where(status: true).count %></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="transactions-container">
                            <div class="panel-transactions panel-secondary">
                                <div class="">
                                    <h3 class="panel-title">Donation transactions</h3>
                                     <% donation.transactions.each do |transaction| %>
                                        <%=   render :partial => 'transactions_container', locals: {transaction: transaction}%>
                                     <% end %>
                                </div>
                            </div>
                        </div>  
                       <p>whateeeveeeer</p>
                    </div> 
                </div>
            </div>
        

app/views/users/_request_transactions_container.html.erb
       
<div class="transactions-container col-md-10 col-md-offset-1">
    <div class="panel-transactions panel-secondary">
        <div class="panel-heading">
            <h3 class="panel-title">Transaction <%= transaction.id %></h3>
        </div>
        <table class="table table-condensed table-responsive table-user-information">
            <tbody>
            <tr>
                <td>Value:</td>
                <td><%= transaction.value %></td>
            </tr>
            <tr>
                <td>Time remaining:</td>
                <td>23 Hours</td>
            </tr>
            <tr>
                <td>Status:</td>
                <% if transaction.status%>
                    <td>Completed</td>
                <% else  %>
                    <td>Pending </td>
                <% end%>
            </tr>
            <tr>
                <td>Sender name:</td>
                <td><%= User.find(transaction.sender_id).name %></td>
            </tr>

            <tr>
                <td>Sender phone:</td>
                <td><%= User.find(transaction.sender_id).phone %></td>
            </tr>

            <tr>
                <td>Sender email:</td>
                <td><%= User.find(transaction.sender_id).email %></td>
            </tr>
            <tr>
                <td>Sender wallet</td>
                <td><%= User.find(transaction.sender_id).btc %></td>
            </tr>
            
            </tbody>
        </table>
        <div class="buttons-container col-md-12"> 
        <div class="col-md-6">
            <%= button_to chats_path(sender_id: current_user.id, recipient_id: transaction.sender_id), class: 'btn btn-primary' do %>
                <i class="fa fa-weixin" aria-hidden="true"></i>
                Message 
            <%end%>
        </div>
        <div class="col-md-6">
            <div class="">

                 <% if transaction.invoice.url %>
                    <div class="col-md-12">
                        <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#img<%=transaction.id%>">Check invoice</button>
                    </div>
                <% else %>
                    <div class="col-md-12">
                        <span>Invoice not sent yet</span>
                    </div>
                <% end  %>
                
            </div>
        </div>
         <div class="col-md-8 col-md-offset-2" style="margin-top:15px;">
            <div class="">
            <% if transaction.status %>
                <h3>Transaction already confirmed</h3>
            <%else%>
                <!--<%= form_tag("/confirm_transaction", method: "post") do %> 
                <%= hidden_field_tag :transaction_id, transaction.id %>
                <%= submit_tag("Confirm transaction", class: "btn btn-info") %>
                
                <%end%>
                 -->  

                 
                <%= link_to "Confirm transaction", transaction_confirm_path(transaction_id: transaction.id), method: :get,  data: { confirm: 'Are you sure?' } %>
                
            <%end%>
            
            </div>
        </div>
        </div> 
        <p>sdasdjalskdjaklsjlk</p>
    </div>
</div>


<% if transaction.invoice.url.present? %>
    <div id="img<%=transaction.id%>" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Upload Screenshot</h4>
                </div>
                <div class ="request-donation-form">
                    <%= image_tag(transaction.invoice.url)%>
                </div>
            </div>
        </div>
    </div>
<%end%>

   

app/views/users/_requests_list.html.erb
        
            <div class="well span8 offset2">

                <div class="row-fluid user-row">
                    <div class="span10">
                        <strong>Code: DGRQ<%= request.id %></strong><br>
                         <strong>Value: <%= request.value %></strong>
                       
                    </div>
                    <div class="span1 dropdown-user" data-for=".r<%= request.id%>">
                        <i class="icon-chevron-down text-muted"></i>
                    </div>
                </div>
                <div class="row-fluid user-infos r<%= request.id%>">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">Request information</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row-fluid">
                                <div class="span6">
                                    <table class="table table-condensed table-responsive table-user-information">
                                        <tbody>
                                        <tr>
                                            <td>Value:</td>
                                            <td><%= request.value %></td>
                                        </tr>
                                        <tr>
                                            <td>Date:</td>
                                            <td><%= request.created_at.to_date %></td>
                                        </tr>
                                        <tr>
                                            <td>Status:</td>
                                            <% if request.completed %>
                                                <td>Completed</td>
                                            <% elsif request.status == "pending"  %>
                                                <td>Pending for donations</td>
                                            <% else request.status == "completed"  %>
                                                <td>Pending for transactions completion</td>
                                            <% end %>
                                        </tr>
                                        <tr>
                                            <td>Value pending for donations</td>
                                            <td><%= request.pending %></td>
                                        </tr>
                                        <tr>
                                            <td>Total transactions</td>
                                            <td><%= request.transactions.count %></td>
                                        </tr>
                                        <tr>
                                            <td>Completed transactions</td>
                                            <td><%= request.transactions.where(status: true).count %></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="transactions-container">
                            <div class="panel-transactions panel-secondary">
                                <div class="">
                                    <h3 class="panel-title">Donation transactions</h3>
                                     <% request.transactions.each do |transaction| %>
                                        <%=   render :partial => 'request_transactions_container', locals: {transaction: transaction}%>
                                     <% end %>
                                </div>
                            </div>
                        </div>  
                       <p>whateeeveeeer</p>
                    </div> 
                </div>
            </div>
       

app/views/users/_transactions_container.html.erb
       
<div class="transactions-container col-md-10 col-md-offset-1">
    <div class="panel-transactions panel-secondary">
        <div class="panel-heading">
            <h3 class="panel-title">Transaction <%= transaction.id %></h3>
        </div>
        <table class="table table-condensed table-responsive table-user-information">
            <tbody>
            <tr>
                <td>Value:</td>
                <td><%= transaction.value %></td>
            </tr>
            <tr>
                <td>Time remaining:</td>
                <td>23 Hours</td>
            </tr>
            <tr>
                <td>Status:</td>
                <% if transaction.status%>
                    <td>Completed</td>
                <% else  %>
                    <td>Pending </td>
                <% end%>
            </tr>
            <tr>
                <td>Sender name:</td>
                <td><%= User.find(transaction.sender_id).name %></td>
            </tr>
            <tr>
                <td>Sender phone:</td>
                <td><%= User.find(transaction.sender_id).phone %></td>
            </tr>

            <tr>
                <td>Receiver email:</td>
                <td><%= User.find(transaction.receiver_id).email %></td>
            </tr>
            <tr>
                <td>Receiver wallet</td>
                <td><%= User.find(transaction.receiver_id).btc %></td>
            </tr>
            
            </tbody>
        </table>
        <div class="buttons-container col-md-12"> 
        <div class="col-md-12">
            <%= button_to chats_path(sender_id: current_user.id, recipient_id: transaction.receiver_id), class: 'btn btn-primary' do %>
               
                    <i class="fa fa-weixin" aria-hidden="true"></i>
                    Message
               
            <%end%>
            
        </div>
        <div class="col-md-12" style="margin-top: 15px;">
            <div class="">
                <% if transaction.invoice.url %>
                    <div class="col-md-6">
                        <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#img<%=transaction.id%>">Check invoice</button>
                    </div>
                    <div class="col-md-6">
                        <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#m<%=transaction.id%>">Reupload receipt</button>
                    </div>
                <% else %>
                    <button type="button" class="btn btn-success btn-md" data-toggle="modal" data-target="#m<%=transaction.id%>">Upload receipt</button>
                <% end  %>
            </div>
        </div>
        </div> 
        <p>sdasdjalskdjaklsjlk</p>
    </div>
</div>

<!-- Upload Image Modal -->
<div id="m<%=transaction.id%>" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Upload Screenshot</h4>
            </div>
            <div class ="request-donation-form">
                <%= form_tag("/add_invoice", method: "post", multipart: true) do %> 
                    <div class="modal-body">
                        <%= file_field_tag :invoice %>
                        <%= hidden_field_tag :transaction_id, transaction.id %>
                    </div>
                    <div class="modal-footer">
                        <div class="col-md-4 col-md-offset-4">
                            <%= submit_tag("Upload", class: "btn btn-primary") %>  
                        </div> 
                    </div>  
                <% end %>    
            </div>
        </div>
    </div>
</div>

<% if transaction.invoice.url.present? %>
    <div id="img<%=transaction.id%>" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Upload Screenshot</h4>
                </div>
                <div class ="request-donation-form">
                    <%= image_tag(transaction.invoice.url)%>
                </div>
            </div>
        </div>
    </div>
<%end%>

   

app/views/users/account_balance.html.erb
  <nav class="own-navbar">
    <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#" style="font-size: 18px;color: #606060;line-height: 20px;">Account Balance</a>
        </div>
    </div>
  </nav>


  <div class="blog-area bg-light blog-page"> 
    <div class="col-md-12">
        <div class="pt-20 text-center">

        <div class="donations-container"> 
            <h1>Donations</h1>
            
                <table class='table table-bordered table-striped responsive-table'>
                    <thead class="blue-text text-darken-4">
                    <tr>
                        <th>Donation</th>
                        <th>Value</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th colspan="3"></th>
                    </tr>
                    </thead>

                    <tbody class="anchorFixcolor hoverTable">
                    <% @donations.each do |donation| %>
                        <tr>
                            <td>DG<%= donation.id %></td>
                            <td><%= donation.value %></td>
                            <td><%= donation.status %></td>
                            <td><%= donation.created_at.to_date %></td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
 
        </div>


        <div class="donations-container"> 
            <h1>Requests</h1>
            <table class='table table-bordered table-striped responsive-table'>
                    <thead class="blue-text text-darken-4">
                    <tr>
                        <th>Donation</th>
                        <th>Value</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th colspan="3"></th>
                    </tr>
                    </thead>

                    <tbody class="anchorFixcolor hoverTable">
                    <% @requests.each do |request| %>
                        <tr>
                            <td>RQ<%= request.id %></td>
                            <td><%= request.value %></td>
                            <td><%= request.status %></td>
                            <td><%= request.created_at.to_date %></td>
                         </tr>
                    <% end %>
                    </tbody>
            </table>

        </div>

        </div>       
    </div>    
  </div>

 

app/views/users/dashboard.html.erb
  <nav class="own-navbar">
    <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#" style="font-size: 18px;color: #606060;line-height: 20px;">WORKSPACE</a>
        </div>
    </div>
  </nav>


  <div class="blog-area bg-light blog-page"> 
    <div class="col-md-12">
        <div class="pt-20 text-center">
            <div class="col-md-6 donations-container" > 
                <h1>Send donation</h1>
                <div class="col-md-4 col-md-offset-4 col-sm-12 ">
                    <div class ="send-donation-form"> 
                        <%= form_tag("/send_donation", method: "post") do %>
                        <%= number_field_tag(:value) %>
                        <%= submit_tag("Send donation", class: "btn btn-primary btn-primary btn-sm") %>
                        <% end %>
                    </div>
                </div>
                <div class ="donations-list col-md-12">
                    <% @donations.each do |donation| %>
                        <div class ="donations-list" style="border: solid 1px; margin: 15px;">
                            <%=   render :partial => 'donation_list', locals: {donation: donation}%>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="col-md-6 donations-container"> 
                <h1>Request donation</h1>
                <div class="col-md-4 col-md-offset-4 col-sm-12 ">
                    <div class ="request-donation-form"> 
                        <%= form_tag("/request_donation", method: "post") do %>
                        <%= number_field_tag(:value) %>
                        <%= submit_tag("Request donation", class: "btn btn-primary btn-primary btn-sm") %>
                        <% end %>
                    </div>
                </div>
                <div class ="donations-list col-md-12">
                    <% @requests.each do |request| %>
                        <div class ="donations-list" style="border: solid 1px; margin: 15px;">
                            <%=   render :partial => 'requests_list', locals: {request: request}%>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>       
    </div>    
  </div>

 

app/views/users/my_referrals.html.erb
  <nav class="own-navbar">
    <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#" style="font-size: 18px;color: #606060;line-height: 20px;">MY REFERRALS</a>
        </div>
    </div>
  </nav>


  <div class="blog-area bg-light blog-page"> 
    <div class="col-md-12">
      <div class="pt-20 text-center">
        <br>
        <div class="row">
          <br>
          <h1>My childrens (Level 1)</h1>
          <br>
          <% @current_user_children.each do |children_first_level|%> 
            <div class="col-md-4" style="margin-bottom: 29px;">
              <h4>
                Nombre: <%=children_first_level.name%> 
                <br>
                Email: <%=children_first_level.email%>
              </h4>
            </div>
          <%end%>
        </div>
        <div class="row">
          <h1>My childrens (Level 2)</h1>
          <% @current_user_children.each do |children_first_level|%> 
            <% children_first_level.children.each do |children_second_level|%>
              <br>
              <div class="col-md-4">
                <h4>
                  PADRE: <%=children_second_level.parent.name%> 
                  <br>
                  Nombre: <%=children_second_level.name%> 
                  <br>
                  Email: <%=children_second_level.email%>
                  <br>
                </h4>
              </div>
            <%end%>
          <%end%>
        </div>
      </div>       
    </div>    
  </div>

 