config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process

  mount ActionCable.server => '/cable'

  root to: 'static#home'
  get '/coming_soon', to: 'static#coming_soon'
  get '/que_es', to: 'static#que_es'
  get '/como_funciona', to: 'static#como_funciona'
  get '/testimonios', to: 'static#testimonios'
  get '/contacto', to: 'static#contacto'

  get '/my_dashboard',  to: 'users#dashboard', as: 'user_dashboard'

  get '/my_referrals',  to: 'users#my_referrals'

  post '/send_donation',  to: 'users#donation_send'

  post '/request_donation', to: 'users#donation_request'

  post '/add_invoice', to: 'transactions#add_invoice'

  get '/confirm_transaction', to: 'transactions#confirm_transaction', as: 'transaction_confirm'

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :donations

  resources :chats do
    resources :messages
  end

  get '/coming_soon',  to: 'static#coming_soon', as: 'coming'

  get '/account_balance',  to: 'users#account_balance'

  get '/news',  to: 'users#news'

end

app/models/donation.rb
class Donation < ApplicationRecord
  # belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  # belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  belongs_to :user
  has_many :transactions, dependent: :destroy
  enum status: { pending: 0, completed: 1 }
  validates :value, presence: true, numericality: { greater_than: 10, less_than: 10000}

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  before_action :set_donation, only: [:show, :edit, :update, :destroy]
 

  def index
    @donations = Donation.all
  end

  # GET /Donations/1
  # GET /Donations/1.json
  def show
  end

  # GET /Donations/new
  def new
    @donation = Donation.new
  end

  # GET /Donations/1/edit
  def edit
  end

  # POST  Send donations
  def sent_donation (value)
    
    @donation = Donation.new(value: 30)
    puts @donation
=begin
    if (current_user.saldo > 0)
      #randon users
        #donation_receptors = User.offset(rand(User.count)).limit(3)

      #testing with the last 3 users on db with records on saldo
        donation_receptors = User.last(3)

      #select the lowest request from the users
        lowest_donation_request = donation_receptors.sort_by(&:saldo).first.saldo
        porcent = lowest_donation_request*20/100

      #Donation amount
       donation = params[:donation][:value]

      while donation > 0
        if donation >= porcent
          donation_receptors.each{|k, v|
            #a[k] == LO QUE ESTA PIDIENDO
            if (donation >= porcent && a[k] >= donation_receptors[k] + porcent)
              donation_receptors[k] += porcent
              donation -= porcent   
            else
              estado[k] = true
            end
          }
        else
          porcent = donation/5.to_f
        end

        if (estado.values.all? {|x| x == true})
          residuo = saldo
          saldo = 0 
        end
      end
    else
      redirect_to donations_path
      flash[:notice] = 'saldo es insuficiente para realizar donación'
      redirect_to donations_root
    end
=end
  end

  # POST /Donations
  # POST /Donations.json
  def create
    @Donation = Donation.new(donation_params)
    respond_to do |format|
      if @donation.save
        format.html { redirect_to @Donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @Donation }
      else
        format.html { render :new }
        format.json { render json: @Donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Donations/1
  # PATCH/PUT /Donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @Donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @Donation }
      else
        format.html { render :edit }
        format.json { render json: @Donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Donations/1
  # DELETE /Donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to Donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:value, :user_id, :balance)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/index.html.erb
<div class="container">
  
  <h1>Donaciones</h1>
<%= link_to  "Hacer donacion", {user: current_user}%>


<%= form_tag("/enviar_donacion", method: "post", class: 'sub-form') do %>
  <%= number_field_tag "donation[value]", "", placeholder: 'Escriba el valor a donar', class: '', type: 'number', required: true%>
  <%= hidden_field_tag 'asd', value: current_user, class: 'asd' %>
  <%= submit_tag("ENVIAR", class: "enviar-sub")%>
<% end %>

<br>
<br>
<br>
<!-- 
<%= link_to "Requerir donacion", request_donation_path, class: 'btn btn-primary'%>
 -->

<div class="container">
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Requerir donacion</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h1>Su saldo es: <%= current_user.saldo%></h1>
        </div>
        <%= form_tag("/requerir_donacion", method: "post", class: 'sub-form') do %>
          <%= number_field_tag "request[:value]", "", placeholder: 'Email', class: 'input-sub form-control', type: 'email', required: true%>
          <%= submit_tag("ENVIAR", class: "enviar-sub")%>
        <% end %>
      </div>
      
    </div>
  </div>
  
</div>


</div>